config/routes.rb
Hijabfard::Application.routes.draw do

  resources :news
  resources :distributions

  devise_for :admins

  get "ckeditor/index"

  resources :categories
  resources :line_items
  resources :carts
  resources :orders

  devise_scope :admin do
    match "admin" => "devise/sessions#new", :as => "admin_sign_in"
  end
  devise_for :users #, :controllers => {:sessions => "users/sessions"}
  devise_scope :user do
    match "sign_out" => "devise/sessions#destroy", :as => "destroy_session_user"
    match "users/sign_up" => "devise/registrations#new", :as => "sign_up"
    get "users/password/new" => "devise/passwords#new", :as => "recover_password", :method => :get

  end

  devise_for :users, :controllers => { :registrations => "registrations" } do
    match "profile/edit" => "registrations#edit", :as => "edit_member_registration"
  end
  match "/pages/:id/edit" => "pages#edit", :as => "pages_edit"
  resources :pages
  resources :products
  root :to => "pages#home", :id => 'home'

  match "*path" => redirect('/404.html')

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_attached_file :avatar, :styles => { :medium => "400x500>", :thumb => "240x380>" }
  default_scope :order => 'title'
  has_many :line_items
  has_many :orders, :through => :line_items
  belongs_to :categories


  before_destroy :ensure_not_referenced_by_any_line_item

  #validates :title, :presence => true, :uniqueness => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}

 # validates :title, :length => {:minimum => 3}

  def self.search(query)
    where("title like ?", "%#{query}%")
  end

  def rating
    line_items.sum(:quantity)
  end

  private

    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end

end

app/controllers/products_controller.rb
# coding: utf-8
class ProductsController < ApplicationController
  before_filter :authenticate_admin!, :except => [:index, :show ]
  # GET /products
  # GET /products.xml
  def index
    @products = Product.search(params[:search])
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @cart = current_cart
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Продукт успешно создан!') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Продукт успешно обновлен.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, :html => { :multipart => true }) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %>
      prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Название" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description, "Описание" %><br />
<!-- START_HIGHLIGHT -->
    <%= f.text_area :description, :rows => 6 %>
<!-- END_HIGHLIGHT -->
  </div>
  <div class="field">
    <%= f.label :price, "Цена" %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :category_id, "Каталог" %><br />
    <%= f.select(:category_id, options_from_collection_for_select(Category.all, :id, :name))  %>
    <%= f.hidden_field(:category_id) %>
  </div>
  <div class="field">
    <%= f.label :avatar, "Изображение" %><br />
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%#= f.label "Категория" %><br />
    <%# for category in Category.all %>
    <%#= check_box_tag 'product[category_id][]', category.id, @product.category_id.include?(category.id), :id => dom_id(category) %>
    <%#= label_tag dom_id(category), category.name, :class => "check_box_label" %>
    <%# end %>
  </div>





  <div class="actions">
    <%= f.submit "Создать" %>
  </div>
<% end %>
<script type="text/javascript">
  $('select#product_category_id').change(function() {
      $('input#product_category_id').attr('value',$('select#product_category_id').val());
      });
</script>

app/views/products/_product.html.erb
<% i=1 %>
<div class="group_gallery" style=" height: 480px;">
<div style="vertical-align: bottom;position:relative; height: 412px; ">
		<%= link_to (image_tag(product.avatar.url(:medium), :class => "round")), product %>
</div>
  <div style=" height: 35px; width: 165px;">
    <p><%= product.title %></p>
    <p><%= product.price %>
      <% if admin_signed_in? %>
        <%= link_to 'Удалить', product,
          :confirm => 'Are you sure?',
          :method => :delete %>
      <% end %>
    </p>
    </div>
<% if i> 3 %>
   <div style="clear: left; padding-bottom: 35px;"></div>
   <% i=0 %>
<% end %>
<% i += 1 %>
</div>

app/views/products/edit.html.erb
<% title "Редактирование" %>
<h2><%= yield(:title) %></h2>
<%= render 'form' %>

<%= link_to 'Показать', @product %> |
<%= link_to 'Назад', products_path %>

app/views/products/index.html.erb
<div id="product_list">
  <% title "Продукты" %>
  <h2><%= yield(:title) %></h2>
  <% if admin_signed_in? %>
    <%= link_to 'Новый продукт', new_product_path, :style => "color: #663366; font-family: 'Myriad Pro',Verdana,Geneva,sans-serif; font-size: 14px; text-decoration: underline;" %>
    <div style="height: 50px; width: 200px; position: relative;">
    <% end %>
  </div>
  <%= render @products %>
</div>

app/views/products/index.js.erb
$('#content').attr('id', 'products');
$("#products").html("<%= escape_javascript(render(@products)) %>");

app/views/products/new.html.erb
<% title "Новый продукт" %>
<h2><%= yield(:title) %></h2>
<%= render 'form' %>

app/views/products/show.html.erb
<div id="show_products">

  <%= image_tag(@product.avatar.url, :alt => @product.title, :class => "round") %>
  <div style="float: right; position: relative; right: 60px; top: 50px; width: 310px;">
    <h2><%= @product.title %></h2>
    <p>Стоимость <%= @product.price %></p>
    <p>Размеры:</p>
    <ul> <li>42</li>
      <li>44</li>
      <li>46</li>
      <li>48</li>
      <li>50</li>
    </ul>
    <%= form_for @product, :url => { :controller => "line_items", :action => "create" }, :html => {:class => "button_to", :method => "post"} do |f| %>
    <p>Количество  <%= f.select( :quantity, [['1',1],['2',2],['3',3],['4',4]]) %></p>
    <%= hidden_field(:product, :quantity) %>
    <%= hidden_field_tag(:product_id, @product.id) %>
    <p>Размер <%= f.select(:size, options_for_select([['42',42],['44',44],['46',46],['48',48],['50',50]], @product.size)) %></p>
    <%= hidden_field(:product, :size) %>
    <%= button_to 'Добавить в корзину' %>
    <% end %>
  </div>
</div>

<% if admin_signed_in? %>
<%= link_to 'Редактировать', edit_product_path(@product) %> |
<%= link_to 'Назад', products_path %>

<% end %>

<script type="text/javascript">
  $('select#product_quantity').change(function() {
      $('input#product_quantity').attr('value',$('select#product_quantity').val());
      });
  $('select#product_size').change(function() {
    $('input#product_size').attr('value',$('select#product_size').val())
    });
    </script>

app/views/products/show_old.html.erb
<div id="show_products">

  <%= image_tag(@product.avatar.url, :alt => @product.title, :class => "round") %>
  <div style="float: right; position: relative; right: 60px; top: 50px; width: 310px;">
    <%= form_for @product, :url => line_items_path(@product), :remote =>true do |f| %>
    <h2><%= f.label :title %></h2>
    <p>Стоимость <%= f.label :price %></p>
    <p>Размеры:</p>
    <ul>
      <li>42</li>
      <li>44</li>
      <li>46</li>
      <li>48</li>
      <li>50</li>
    </ul>
    <p>Количество  <%= f.select("quantity", options_for_select([['1',1],['2',2],['3',3],['4',4]])) %></p>
    <p>Размер <%= f.select("size", options_for_select([['42',1],['44',2],['46',3],['48',4],['50',5]])) %></p>
    <%= f.submit 'Добавить в корзину'  %>
    <% end %>
  </div>
</div>

<% if user_signed_in? %>
<%= link_to 'Редактировать', edit_product_path(@product) %> |
<%= link_to 'Назад', products_path %>
  
<% end %>