config/routes.rb
Hijabfard::Application.routes.draw do

  resources :news
  resources :distributions

  devise_for :admins

  get "ckeditor/index"

  resources :categories
  resources :line_items
  resources :carts
  resources :orders

  devise_scope :admin do
    match "admin" => "devise/sessions#new", :as => "admin_sign_in"
  end
  devise_for :users #, :controllers => {:sessions => "users/sessions"}
  devise_scope :user do
    match "sign_out" => "devise/sessions#destroy", :as => "destroy_session_user"
    match "users/sign_up" => "devise/registrations#new", :as => "sign_up"
    get "users/password/new" => "devise/passwords#new", :as => "recover_password", :method => :get

  end

  devise_for :users, :controllers => { :registrations => "registrations" } do
    match "profile/edit" => "registrations#edit", :as => "edit_member_registration"
  end
  match "/pages/:id/edit" => "pages#edit", :as => "pages_edit"
  resources :pages
  resources :products
  root :to => "pages#home", :id => 'home'

  match "*path" => redirect('/404.html')

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  
  def total_price
    product.price * quantity
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_filter :authenticate_admin!, :except => [:create, :update]

  # GET /line_items
  # GET /line_items.xml
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.xml
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.xml
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.xml
  def create
    @cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id, params[:product][:quantity], params[:product][:size])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @cart }
        format.js { @current_item = @line_item }
        format.xml  { render :xml => @line_item, :status => :created, :location => @line_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @line_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.xml
  def update
     @cart = current_cart
     quantity = params[:quantity].to_i;
    #@line_item = LineItem.find(params[:id])
    if current_cart
      @line_item = LineItem.where(:id => params[:id]).first
       unless quantity <= 0
        @line_item.quantity = quantity
      else
        @line_item.destroy
      end
    end


    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to(@line_item, :notice => 'Line item was successfully updated.') }
        format.xml  { head :ok }
        format.js { @current_item = @line_item }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @line_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.xml
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to(line_items_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% i=1 %>
<div class="group_gallery" style=" height: 520px;">
  <div style="vertical-align: bottom;position:relative; height: 412px; ">
    <%= image_tag(line_item.product.avatar.url(:thumb), :class => "round")%>
  </div>
  <div style=" height: 35px; width: 160px">
    <h2><%= line_item.product.title %></h2>
    <h3>Размер <%= line_item.size %></h3>
    <table style="height: 10px;"> <tr>
        <td style="width: 15px;">
          <%= button_to "-", line_item_path(  :quantity => (line_item.quantity - 1), :id => line_item), :remote =>true, :method => :put  %>
        </td>
        <td id="quantity_item" style="width: 15px; text-align: center;">
          <%= line_item.quantity %>
        </td>
        <td style="width: 15px;">
          <%= button_to "+", line_item_path( :quantity => (line_item.quantity + 1), :id => line_item), :remote =>true, :method => :put %>
        </td>
        <td style="font-size: 12pt; font-family: 'Myriad Pro', Verdana, Geneva, sans-serif;">
          &times; <%= line_item.product.price %> руб.</td></tr>
    </table>
  </div>
  <% if i> 3 %>
    <div style="clear: left; padding-bottom: 35px;"></div>
    <% i=0 %>
  <% end %>
  <% i+= 1 %>
</div>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s",
            line_item.quantity,
            truncate(line_item.product.title, :length => 50)) %>

app/views/line_items/_table_cart.html.erb
<table style="height: 10px;"> <tr>
        <td style="width: 15px;">
    <%= button_to "-", line_item_path(  :quantity => (line_item.quantity - 1), :id => line_item), :remote =>true, :method => :put  %>
        </td>
        <td id="quantity_item<%= line_item.id %>" style="width: 15px; text-align: center;">
    <%= line_item.quantity %>
        </td>
        <td style="width: 15px;">
    <%= button_to "+", line_item_path( :quantity => (line_item.quantity + 1), :id => line_item), :remote =>true, :method => :put %>
        </td>
        <td style="font-size: 22px;">
     &times; <%= line_item.product.price %> руб.</td></tr>
</table>

app/views/line_items/create.js.erb
$("#notice").hide();
$("#cart").html("<%= @cart.total_price %> руб.");
if (<%= @cart.total_items %> >= 1) {
$("#cart").show('slow');
<!--$.jGrowl("<%= escape_javascript(render(@cart)) %>");$.jGrowl("<%= @current_item.product.image_url %>");-->
};


function createTable()
    {

    var newElem=document.createElement("table");
    newElem.border=1;
    newElem.id="nova";

    var newRow=newElem.insertRow(0);
    var newCell = newRow.insertCell(0);
    newCell.width="100";
    newCell.align="center";
    newCell.innerHTML="<img class=\"round\" src=\"images/<%= @current_item.product.image_url %>\" border=\"0\"/>";


    var newCell = newRow.insertCell(-1);
    newCell.width="100";
    newCell.align="center";
    newCell.innerText="<%=@line_item.product.title %> ";

    var newRow=newElem.insertRow(1);
    var newCell = newRow.insertCell(0);
    newCell.width="100";
    newCell.align="center";

    //addText=document.createTextNode
    newCell.innerText=("<%=@current_item.total_price%> руб.");
    //newCell.appendChild(addText);

    var newCell = newRow.insertCell(-1);
    newCell.width="100";
    newCell.align="center";
    addElem=document.createElement("b");
    addText=document.createTextNode(" ");//генерируем текстовый узел
    addElem.appendChild(addText);//созданный текстовый узел добавляем к новому элементу (addElem)
    newCell.appendChild(addElem);//полученный узел (addElem) добавляем в ячейку

    document.body.appendChild(newElem);//прописываем созданную таблицу на страницу
    }

var newdiv = document.createElement('div');
var divIdName = 'new';
newdiv.setAttribute('id',divIdName);
newdiv.style.width = "200px";
newdiv.style.height = "300px";
newdiv.style.top = "-140px";
newdiv.style.position = "relative";

document.body.appendChild(newdiv);

<% if @line_item.product_id == @current_item.product_id %>

$.jGrowl('<h3>Добавлен!</h3>',{
    beforeOpen: function(e,m,o)  {
           createTable();
           $("#new").append($("#nova"));
           $("div#jGrowl").append($("#new"));

    },
    beforeClose: function(e,m)  {

           $("#nova").remove();
           $("#new").remove();


    },
     close: function(e,m,o)  {

           $("#nova").remove();


    }
});
<% end%>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Cart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.product_id %></td>
    <td><%= line_item.cart_id %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @line_item.product_id %>
</p>

<p>
  <b>Cart:</b>
  <%= @line_item.cart_id %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/update.js.erb
$('#cart_table').html("<%= escape_javascript(render(@cart.line_items))%>");
$("#cart_total_items").html("Корзина (<%= @cart.total_items %>)");
$(".price").html("Всего <%= @cart.total_price %> руб.");